<HTML>

    <HEAD>


      <TITLE>My Navigation Page</TITLE>

    </HEAD>

    <BODY>

 

      <FORM METHOD="post" ACTION="my_page.asp">

      <P>

        <FONT COLOR="#000080">

          Please select a page:</FONT>

        <SELECT NAME="Category" >
          <OPTION SELECTED>Home</OPTION>
          <OPTION>About Me</OPTION>
          <OPTION>About HTML</OPTION>
          <OPTION>About ASP</OPTION>
        </SELECT>

        <INPUT TYPE="submit" VALUE="GO!" NAME="Go">

        </P>
      </FORM>

 

    </BODY>

 

  </HTML>

